### ISSUE TITLE
New shapes

### ISSUE THREAD

**Issue by benju69** [DanielMartinus/Konfetti#11]
I am thinking it would be nice to have more shapes :) Rectangles (not just squares), stars and long rectangles maybe (or serpentine streamers)

**Comment by DanielMartinus** [comment]
I'm checking what I can do about this. The goal here is not to create another particle library, there are many others which accomplish this. So I want to keep true to confetti shapes. As you mentioned, variations in rectangles and ideally serpentine streamer would be preferable indeed.
 
Any pull request is welcome

**Comment by Akshshr** [comment]
Hey Daniel, Awesome work! I second this, how are the different shapes coming along? 

Would like custom shapes, in best case scenario shapes loaded directly from drawables or XML shapes

**Comment by DanielMartinus** [comment]
@Akshshr I do not have any particular shapes to add right now. Long rectangles would be a nice first to start on because they'll do very well in a confetti particle system like this. Other shapes like serpentines I haven't give a thought on how to accomplish that yet.

**Comment by ben-j69** [comment]
Why not just little stars ?

**Comment by Akshshr** [comment]
The smartest thing would be to support any drawable

**Comment by ronakmob** [comment]
It would be nice if we can set confetti image, so we can add an image of any shape.

**Comment by barakhadar** [comment]
I strongly agree with @Akshshr , an option to set any drawable(s) will make this project even better than it already is. 

@DanielMartinus we all hope you'll give it some **serious consideration**. For instance, I need to set hearts and stars, others need snowflakes, emojis, and the list goes on and on... Think how many people wanted to use this great library, but eventually chose some other library (and probably not as good) just because it's missing one simple option...

**Comment by mattprecious** [comment]
@DanielMartinus, are you receptive to PRs for this? I have some ideas that won't require many changes to the library.

**Comment by DanielMartinus** [comment]
I've been holding back adding custom shapes to Konfetti due to the reasons mentioned [earlier](https://github.com/DanielMartinus/Konfetti/issues/11#issuecomment-383005713) in this Issue. I'm super happy that @mattprecious implemented a way of adding custom shapes which doesn't affect the performance and is also very easy to use. 🎉

**Comment by DanielMartinus** [comment]
It has been merged and released in version 1.2.0 of Konfetti.
