### ISSUE TITLE
konfetti only comes from top left side of the view

### ISSUE THREAD

**Issue by keisa97** [DanielMartinus/Konfetti#218]
hello, got some wired situation hope you can help me with
when i use the function with button, the konfetti shows great (from the middle)
setKonfetti func:

```Kotlin
fun setKonfetti(view: KonfettiView){
        view.build()
            .addColors(Color.YELLOW, Color.GREEN, Color.MAGENTA,Color.RED, Color.BLUE)
            .setDirection(0.0, 359.0)
            .setSpeed(1f, 5f)
            .setFadeOutEnabled(true)
            .setTimeToLive(2000L)
            .addShapes(nl.dionsegijn.konfetti.models.Shape.Square, nl.dionsegijn.konfetti.models.Shape.Circle)
            .addSizes(Size(12))
            .setPosition(-50f, view.width + 50f, -50f, -50f)
            .streamFor(300, 5000L)
    }
```

```Kotlin
tvNextItem.setOnClickListener {
            setKonfetti(viewKonfetti)
        }

```

<img src="https://user-images.githubusercontent.com/60548594/98227837-75e20400-1f60-11eb-9f99-9c1949872851.jpg" width=300/>

but if i do like that:
```Kotlin

        if (clothScannedSuccess){
            setKonfetti(viewKonfetti)
            clothScannedSuccess = false
        }
```
the konfetti comes out only from the left side

<img src="https://user-images.githubusercontent.com/60548594/98227830-71b5e680-1f60-11eb-9e17-0c130fb750bf.jpg" width=300/>

any idea what i'm doing wrong?

**Comment by DanielMartinus** [comment]
Hey @keisa97,

It could very well be that in the second scenario the KonfettiView isn't properly initialized yet.

In above code you see that the following line is being used:
```Kotlin
.setPosition(-50f, view.width + 50f, -50f, -50f)
```

since it's using view.width I suspect that this is returning 0 instead of the actual width of the view because the view isn't fully rendered yet.

You can solve this in different ways. For example by using ViewtreeObserver observe when the view is drawn or only call this when you're sure the layout is fully drawn.

You can read more about this in this StackOverview answer: https://stackoverflow.com/a/24035591

**Comment by keisa97** [comment]
hey @DanielMartinus 
 thanks again for your great answer!
that code solved my problem(view isn't fully rendered yet)
*Kotlin
`
     view.post {
               if (clothScannedSuccess){
                setKonfetti(viewKonfetti)
                clothScannedSuccess = false
              }

        }

`
