### ISSUE TITLE
Change Position or Direction of konfettiView?

### ISSUE THREAD

**Issue by BalasundarKartheesan** [DanielMartinus/Konfetti#55]
I want to Change position from Top Center to Bottom how to fix this?

**Comment by DanielMartinus** [comment]
Sorry, I'm not exactly sure what you mean. Can you try and explain it with a bit more context?

**Comment by BalasundarKartheesan** [comment]
I am Trying to Change the Direction from top Center to Bottom it Can't happend  the konfettiView. It Was Only Happend Listener for the KonfettiView.

**Comment by DanielMartinus** [comment]
I'm still not sure what you exactly mean.

Do you mean you want the konfetti to go up instead of falling down? So the ability to change the gravity? Or do you want to let the konfetti appear at the bottom of the screen? 

If the latter is the case you can set the position by:

```Kotlin
val maxHeight = viewKonfetti.height
val maxWidth = viewKonfetti.width

viewKonfetti.
  ... // Leaving none important bits out
  .setPosition(maxHeight, maxHeight, 0, maxWidth)
```

This way the konfetti is positioned at the bottom of the KonfettiView and appears from the entire width of the view.

**Comment by DanielMartinus** [comment]
Closing this issue due to no response
