### ISSUE TITLE
The kofetti does not display correctly when it is called in fragment OnViewCreated

### ISSUE THREAD

**Issue by DaireJN** [DanielMartinus/Konfetti#74]
in my fragment calling the startConfetti method in onCreateView results in the following

```
 override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        startConfetti()
    }
```
![screenshot_20190308-145239](https://user-images.githubusercontent.com/28805987/54035858-3030cf00-41b2-11e9-8789-c8d9dfc9aa43.png)

however if i delay the startConfetti method call the animation works as expected
```
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        Timer().schedule(object : TimerTask() {
            override fun run() {
               startConfetti()
            }
        }, 100L)
    }
```
![screenshot_20190308-145249](https://user-images.githubusercontent.com/28805987/54035969-69693f00-41b2-11e9-84bc-ce121d0a9b76.png)

here is the startConfettiMethod
```
private fun startConfetti() {
        viewKonfetti.build()
            .addColors(Color.YELLOW, Color.GREEN, Color.MAGENTA)
            .setDirection(0.0, 359.0)
            .setSpeed(4f, 7f)
            .setFadeOutEnabled(true)
            .setTimeToLive(2000L)
            .addShapes(Shape.RECT, Shape.CIRCLE)
            .addSizes(Size(12), Size(16, 6f))
            .setPosition(-50f, viewKonfetti.width + 50f, -50f, -50f)
            .streamFor(300, 5000L)
    }
```

**Comment by DanielMartinus** [comment]
Hi @DaireJN,

This is indeed correct. In `onViewCreated` the layout isn't measured yet and so the width is 0. So calling ` viewKonfetti.width` is actually returning 0. I'd suggest not to use a timer to make sure the layout is measured since this can result in timing issues.
A more proper way to make sure the layout is measured is to listen to the viewTreeObserver.

See #71 discussing the same problem including this comment with an explanation: https://github.com/DanielMartinus/Konfetti/issues/71#issuecomment-438470185
